server:
  port: 0

spring:
  application:
    name: LiveLocationModule
  kafka:
    bootstrap-server: localhost:29092,localhost:39092
    group-id: poc-live-location-collector
    incoming-topic: poc-live-location-data
    outgoing-topic: poc-update-external-device